### ISSUE TITLE
[S1 - PBI1] Membuat halaman register

### ISSUE THREAD

**Issue by madrioo** [SI-RPL-2023/SI4402_228_TITIPAN#3]

**Comment by Cttraaaaaa** [comment]
S1 - PBI1 : Fitur register
User sebagai pemakai jasa ingin melakukan register

Lama pengerjaan : 3 hari

Activity Diagram : 
<img width="103" alt="image" src="https://user-images.githubusercontent.com/115629732/232316781-e97638c9-096d-4358-b740-e6ab9ddb0712.png">

Review Codingan :
<img width="869" alt="image" src="https://user-images.githubusercontent.com/115629732/232317396-0b0880e5-b6a1-4589-8dc2-001c0cd39673.png">

** Berdasarkan hasil review code, saya melihat untuk backend belum terhubung. Bisa dilanjutkan pada Sprint selanjutnya
