### ISSUE TITLE
[S1 - PBI3] Membuat halaman landing page

### ISSUE THREAD

**Issue by madrioo** [SI-RPL-2023/SI4402_228_TITIPAN#5]

**Comment by afifahhasnawaf** [comment]
done. 
![image](https://user-images.githubusercontent.com/126322233/227937728-8780c1b7-59d1-47ff-892b-14b9b845ff50.png)

**Comment by Cttraaaaaa** [comment]
S1 - PBI3 : Fitur Landing Page
User sebagai pemakai jasa ingin melihat Layanan yang ada pada TITIPAN

Lama pengerjaan : 3 hari

Activity Diagram :
<img width="241" alt="image" src="https://user-images.githubusercontent.com/115629732/232318998-87aef20c-78e1-4aff-8271-f5d4cdc5bc9f.png">

** Termasuk pada activity diagram layanan titipan

Review Codingan : 
<img width="877" alt="image" src="https://user-images.githubusercontent.com/115629732/232319109-1e084f7a-cee7-47bf-a21d-57ea6f68e058.png">
