### ISSUE TITLE
[S1 - PBI4] Membuat halaman jasa pindahan

### ISSUE THREAD

**Issue by madrioo** [SI-RPL-2023/SI4402_228_TITIPAN#6]

**Comment by yaelahjed** [comment]
done
![Screenshot (3752)](https://user-images.githubusercontent.com/115638012/228720928-ea95d81b-4eab-4724-a7fa-491b00babecd.png)

**Comment by Cttraaaaaa** [comment]
S1 - PBI4 : Fitur Halaman Jasa Pindahan
User sebagai pemakai jasa ingin melihat layanan Jasa Pindahan

Lama pengerjaan : 3 hari

Activity Diagram :
<img width="240" alt="image" src="https://user-images.githubusercontent.com/115629732/232319294-093dc58c-885c-488f-9182-8a5b59797371.png">

Review Codingan : 
<img width="883" alt="image" src="https://user-images.githubusercontent.com/115629732/232319364-292fb22f-811f-4a3d-94b0-c332ef7ea37a.png">
