### ISSUE TITLE
[S1 - PBI5] Membuat halaman jasa pengiriman

### ISSUE THREAD

**Issue by madrioo** [SI-RPL-2023/SI4402_228_TITIPAN#7]

**Comment by hananfarizta** [comment]
done.
![Screenshot 2023-04-04 at 13 01 36](https://user-images.githubusercontent.com/80895950/229701408-5bb72f59-5c39-44d9-82eb-a02789893828.png)

**Comment by Cttraaaaaa** [comment]
S1 - PBI5 : Fitur Halaman Jasa Pengiriman 
User sebagai pemakai jasa ingin melihat halaman jasa pengiriman

Lama pengerjaan : 3 hari

Activity Diagram :
<img width="236" alt="image" src="https://user-images.githubusercontent.com/115629732/232319489-56d3191b-9af6-4a4c-b541-b844adc9e6b1.png">

Review Codingan : 
<img width="874" alt="image" src="https://user-images.githubusercontent.com/115629732/232319542-a354da2a-7608-4550-8377-703112033168.png">
