### ISSUE TITLE
[S1 - PBI6] Membuat halaman jasa penyimpanan

### ISSUE THREAD

**Issue by madrioo** [SI-RPL-2023/SI4402_228_TITIPAN#8]

**Comment by hananfarizta** [comment]
done.
![Screenshot 2023-04-04 at 13 01 47](https://user-images.githubusercontent.com/80895950/229701514-6c75d20e-5354-4676-a3fc-7702eb6f3c84.png)

**Comment by Cttraaaaaa** [comment]
S1 - PBI6 : Fitur Halaman Jasa Penyimpanan 
User sebagai pemakai jasa ingin melihat layanan jasa penyimpanan

Lama pengerjaan : 3 hari

Activity Diagram : 
<img width="235" alt="image" src="https://user-images.githubusercontent.com/115629732/232319796-c58315b7-7c76-424d-bc03-229c1585268e.png">

Review Codingan : 
<img width="895" alt="image" src="https://user-images.githubusercontent.com/115629732/232319907-74a3e40a-58c0-4c39-9728-4df0d45f9f68.png">
